# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Robinson
email: alexander.robinson@awi.de
description: > # this means to ignore newlines until "baseurl:"
  Ram√≥n y Cajal Professor<br>    
  at Universidad Carlos III de Madrid
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alex-robinson.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  alex-robinson

# Build settings
markdown: kramdown
